import { Drone, FleetKPI, ModuleData, MaintenanceLog } from '../types'

export const mockFleetKPI: FleetKPI = {
  fleetAvailability: 90,
  activeFlights: 3,
  charging: 3,
  criticalAlerts: 1,
}

export const mockDrones: Drone[] = [
  {
    id: '001',
    name: 'Orca 001',
    status: 'flight',
    soh: 98,
    soc: 72,
    voltage: 402.5,
    temperature: 42,
    cycleCount: 298,
  },
  {
    id: '002',
    name: 'Orca 002',
    status: 'idle',
    soh: 95,
    soc: 88,
    voltage: 400.2,
    temperature: 38,
    cycleCount: 215,
  },
  {
    id: '003',
    name: 'Orca 003',
    status: 'flight',
    soh: 97,
    soc: 78,
    voltage: 398.5,
    temperature: 41,
    cycleCount: 189,
  },
  {
    id: '004',
    name: 'Orca 004',
    status: 'fault',
    soh: 82,
    soc: 45,
    voltage: 385.2,
    temperature: 55,
    cycleCount: 520,
  },
  {
    id: '005',
    name: 'Orca 005',
    status: 'charging',
    soh: 91,
    soc: 65,
    voltage: 395.8,
    temperature: 39,
    cycleCount: 342,
  },
  {
    id: '006',
    name: 'Orca 006',
    status: 'idle',
    soh: 96,
    soc: 92,
    voltage: 401.5,
    temperature: 37,
    cycleCount: 198,
  },
  {
    id: '007',
    name: 'Orca 007',
    status: 'charging',
    soh: 88,
    soc: 55,
    voltage: 392.8,
    temperature: 40,
    cycleCount: 412,
  },
  {
    id: '008',
    name: 'Orca 008',
    status: 'flight',
    soh: 94,
    soc: 68,
    voltage: 397.2,
    temperature: 43,
    cycleCount: 275,
  },
  {
    id: '009',
    name: 'Orca 009',
    status: 'charging',
    soh: 93,
    soc: 48,
    voltage: 391.5,
    temperature: 38,
    cycleCount: 305,
  },
  {
    id: '010',
    name: 'Orca 010',
    status: 'idle',
    soh: 99,
    soc: 95,
    voltage: 403.8,
    temperature: 36,
    cycleCount: 142,
  },
]

export const mockModules: ModuleData[] = [
  { id: 'MOD-01', name: 'Module 01', status: 'normal', soc: 88, soh: 99.2, voltage: 44.2 },
  { id: 'MOD-02', name: 'Module 02', status: 'normal', soc: 87, soh: 98.9, voltage: 44.1 },
  { id: 'MOD-03', name: 'Module 03', status: 'normal', soc: 88, soh: 99.0, voltage: 44.2 },
  { id: 'MOD-04', name: 'Module 04', status: 'normal', soc: 86, soh: 98.5, voltage: 44.0 },
  { id: 'MOD-05', name: 'Module 05', status: 'normal', soc: 89, soh: 99.3, voltage: 44.3 },
  { id: 'MOD-06', name: 'Module 06', status: 'normal', soc: 88, soh: 99.1, voltage: 44.2 },
  { id: 'MOD-07', name: 'Module 07', status: 'normal', soc: 87, soh: 98.8, voltage: 44.1 },
  { id: 'MOD-08', name: 'Module 08', status: 'warning', soc: 84, soh: 96.5, voltage: 43.9 },
  { id: 'MOD-09', name: 'Module 09', status: 'normal', soc: 88, soh: 99.2, voltage: 44.2 },
  { id: 'MOD-10', name: 'Module 10', status: 'normal', soc: 89, soh: 99.4, voltage: 44.3 },
]

export const mockMaintenanceLogs: MaintenanceLog[] = [
  {
    id: '1',
    type: 'critical',
    title: 'Thermal Management Override',
    module: 'Module #402-A',
    reason: 'Exceeding thermal variance threshold during climb phase.',
    confidence: 99.2,
    impact: 'Prevents thermal runaway risk',
    action: 'Initiate Cooling Protocol',
  },
  {
    id: '2',
    type: 'optimization',
    title: 'Voltage Calibration',
    module: 'Sub-array Group B',
    reason: 'Minor drift detected in sub-array B voltage output.',
    confidence: 94.0,
    impact: '+2.5% Range Efficiency',
    action: 'Calibrate at Next Charge',
  },
  {
    id: '3',
    type: 'warning',
    title: 'Cycle Count Discrepancy',
    module: 'Fleet Sector 2',
    reason: 'Logged cycles deviate from estimated usage pattern.',
    confidence: 88.5,
    impact: 'Possible -40 Cycles Lifetime',
    action: 'Review Logs',
  },
  {
    id: '4',
    type: 'optimization',
    title: 'Pre-Flight Cooling',
    module: 'Global Fleet Settings',
    reason: 'Ambient temperature forecast > 35°C for next scheduled routes.',
    confidence: 96.8,
    impact: 'Reduces peak temp by 8°C',
    action: 'Adjust Cooling Schedule',
  },
]
